### PR TITLE
Basic Components

### PR DESCRIPTION
**Pull request by cannarelladev**
This PR will include some basic common components to be used everywhere on the frontend.

- [x] Product Card
- [x] Category Card
- [x] Navbar
- [x] Sidebar (basket)
- [x] Main Content

### CODE REVIEW

**Review by KatellGourlet — APPROVED** [review]

**Review by djemar — CHANGES_REQUESTED** [review]
Check sonar report before merging (bugs and code smells). Also, let's consider testing before merging PRs.

**Comment by cannarelladev** [comment]
i agree with you but this one is like an initialization PR so can be merged. about testing i don't know how to do it,  i didn't do it before

**Comment by cannarelladev** [comment]
each bug and code smell has been removed

**Review by djemar — DISMISSED** [review]

**Review by djemar — APPROVED** [review]
Coverage is fine now! Ready to be merged.

**Pull request merged**
